### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by skoskipaa** [LauriTahvanainen/GameTracker#1]
Ladattu ma 10.6. klo 20.21

**Dokumentaatio**

Projektin dokumentaatio on todella hyvällä mallilla. Käyttäjätarinat ovat yksityiskohtaisia, huolellisesti laadittuja ja ajan tasalla toteutettujen toiminnallisuuksien suhteen.

**Koodi**

Rakenne on selkeä ja toiminnallisuudet on jaettu kansioihin loogisesti. Tiedostonnimistä voi päätellä, mitä ne sisältävät. Projekti noudattaa rakenteeltaan ja toteutukseltaan kurssin materiaalia. Muuttujat ja funktiot on nimetty johdonmukaisesti ja kuvailevasti.

Koodista löytyi huomautettavaa lähinnä muuttujien kirjoitustavasta esimerkiksi seuraavista kohdista:

listuser.html: Olion muuttujat on kirjoitettu isolla alkukirjaimelle (esim. obs.Havaintonumero).
userinfo.html: Muuttuja User kirjoitettu isolla alkukirjaimella

Lomakkeiden nimet (luokat) tulisi kirjoittaa isolla alkukirjaimella (nyt esim. addNewAnimalForm, voisi olla selkeämmin vain AnimalForm). (Eli luokkien nimet isolla alkukirjaimella ja kaikki muut muuttujat pienellä alkukirjaimella.)

**Sovellus ja käytettävyys**

Sovellukseen ei valitettavasti päässyt kirjautumaan Herokussa testatessani sitä ma 10.6. sekä to 13.6. Annettu testikäyttäjätunnus aiheutti virheilmoituksen ‘Internal server error’ ja uuden käyttäjän luominen ei myöskään onnistunut, vaan sovellus ilmoitti kokeiltujen käyttäjänimien olevan jo käytössä. Sovellus ei meinannut toimia aluksi paikallisestikaan (Exec format error), mutta Werkzeugin muuttaminen versioon 0.14.1 korjasi ongelman. (Testikoneeni käyttöjärjestelmä on MacOS ja omassa projektissani uudempi versiokin toimii moitteetta. Jostain syystä Flaskin versio oli myös eri kuin omassa projektissani, mutta sillä ei ollut vaikutusta.) Testasin siis sovellusta lokaalisti.

Ulkoasultaan sivut olivat selkeät ja toiminnallisuudet löytyivät helposti yläpalkista. Käytettävyyden kannalta voisi olla selkeämpää, jos rekisteröitymissivulta ohjattaisiin suoraan kirjautumiseen. Nyt piti hetki miettiä, mitä seuraavaksi tehdään, kun rekisteröinti oli onnistunut. (Sainpa tästä idean korjata tuon omaankin sovellukseeni…)

Havainnon lisäämisessä alasvetovalikko eläimille on kätevä. Käytettävyyttä voisi vielä parantaa linkki eläimen lisäämiseen sivulle. Nyt yritin ensimmäiseksi lisätä havainnon, mutta järjestelmässä ei ollut eläimiä, jolloin lisäys ei onnistunutkaan. Helppo ja nopea muutos olisi laittaa eläimen valinta ensimmäiseksi vaihtoehdoksi, jolloin käyttäjä ei turhaan syöttäisi kaikkia muita tietoja ennen kuin huomaisi puutteen.

Eläimen syöttö onnistui helposti. Pohdin tosin, onko URL-osoitteen syöttö lisätietokenttään välttämätöntä tietoa. Havainnon syöttö ei vielä toiminut loppuun saakka, koska välinettä ei voinut syöttää ja validointi ei sallinut kentän jättämistä tyhjäksi.

Validoinnit on toteutettu huolellisesti ja lähes kaikille kentille. Käytettävyyden kannalta kannattaa vielä ehkä miettiä, mitkä kaikki kentät ovat tietokannassa välttämättömiä sovelluksen toiminnalle. Käytettävyyden nimissä voisi olla kätevämpää, jos joitain kenttiä voisi jättää tyhjäksikin.

Salasanan vaihto onnistui, samoin kuin käyttäjätilin poisto.

Kokonaisuutena sovellus on oikein hyvällä mallilla ja toiminnallisuuksia on toteutettu jo runsaasti. Flash-tekstit toimintojen yhteydessä olivat mukava lisä ja parantavat käytettävyyttä ja vuorovaikutusta. Antoisaa loppuprojektia ja koodausintoa!

**Comment by LauriTahvanainen** [comment]
Kiitos! Erittäin hyödyllinen katselmointi!
